// export const WEBSITE_BASE_URL = 'https://rabbitmart-cm.vercel.app'
// export const PRODUCTS_BASEURL = 'https://rabbitmart-products.vercel.app/products'
// export const ORDERS_BASEURL = 'https://rabbitmart-orders.vercel.app/orders'
// export const SHIPPING_BASEURL = 'https://rabbitmart-shipping.vercel.app/shipping'
// export const NOTIFICATIONS_BASEURL = 'https://rabbitmart-notifications.vercel.app/notifications'
// export const PAYMENTS_BASEURL = 'https://rabbitmart-payments.vercel.app/payments'
// export const USER_BASEURL = 'https://rabbitmart-users.vercel.app/me'

// export const WEBSITE_BASE_URL = 'https://fb9mfhvk-3000.asse.devtunnels.ms'
// export const PRODUCTS_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/products'
// export const ORDERS_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/orders'
// export const SHIPPING_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/shipping'
// export const NOTIFICATIONS_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/notifications'
// export const PAYMENTS_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/payments'
// export const USER_BASEURL = 'https://fb9mfhvk-5000.asse.devtunnels.ms/me'

export const WEBSITE_BASE_URL = 'https://greengo-mart-auefb3fnccc6ebf8.canadacentral-01.azurewebsites.net'
export const PRODUCTS_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/products'
export const ORDERS_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/orders'
export const SHIPPING_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/shipping'
export const NOTIFICATIONS_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/notifications'
export const PAYMENTS_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/payments'
export const USER_BASEURL = 'https://greengo-server-hadqcreshwafhzeh.canadacentral-01.azurewebsites.net/me'